CREATE DATABASE TABLA_PERIODICA;

CREATE TABLE USUARIOS (
	    NOMBRE NVARCHAR(50),
        APELLIDO NVARCHAR(50),
        TIPO_USUARIO CHAR(3),
        MAIL NVARCHAR(50) PRIMARY KEY,
        CONTRASENIA NVARCHAR(15)
)

CREATE TABLE PREGUNTAS (
	    MAIL_ALUMNO NVARCHAR(50) FOREIGN KEY REFERENCES	USUARIOS(MAIL),
        PREGUNTA NVARCHAR(100),
        RESPUESTA NVARCHAR(300)
)

CREATE TABLE ELEMENTO (
	    NRO_ATOMICO INT PRIMARY KEY,
		NOMBRE NVARCHAR(40),
		SIMBOLO NVARCHAR(3),
		VALENCIA NVARCHAR(20),
		ELECTRONEGATIVIDAD DECIMAL (4,2),
		CONF_ELECTRONICA NVARCHAR(40),
		MASA_ATOMICA DECIMAL(8,5),
		DETALLES NVARCHAR(150),
		IMAGEN NVARCHAR(50),
		PTO_EBULLICION DECIMAL(6,2),
		PTO_FUSION DECIMAL(6,2),
		DENSIDAD DECIMAL(6,3)
)

CREATE TABLE MENSAJES (
	ID_MENSAJE INT PRIMARY KEY IDENTITY(1,1),
	DE_USUARIO NVARCHAR(50) NOT NULL FOREIGN KEY REFERENCES	USUARIOS(MAIL),
	A_USUARIO NVARCHAR(50) NOT NULL FOREIGN KEY REFERENCES	USUARIOS(MAIL),
	MENSAJE NVARCHAR(200) NOT NULL,
	ELEMENTO INT FOREIGN KEY REFERENCES ELEMENTO(NRO_ATOMICO),
	FECHA DATETIME,
)

