CREATE DATABASE TABLA_PERIODICA;

SET DATEFORMAT dmy;

CREATE TABLE USUARIOS (
	    NOMBRE NVARCHAR(50),
        APELLIDO NVARCHAR(50),
        TIPO_USUARIO CHAR(3),
        MAIL NVARCHAR(50) PRIMARY KEY,
        CONTRASENIA NVARCHAR(15)
)

CREATE TABLE TIPO_ELEMENTO (
		ID INT PRIMARY KEY,
		NOMBRE NVARCHAR(30)
);

CREATE TABLE ELEMENTO (
	    NRO_ATOMICO INT PRIMARY KEY,
		NOMBRE NVARCHAR(40) NOT NULL,
		SIMBOLO NVARCHAR(3) NOT NULL,
		MASA_ATOMICA NVARCHAR(10) NOT NULL,
		TIPO INT NOT NULL FOREIGN KEY REFERENCES TIPO_ELEMENTO(ID),
		GRUPO INT NOT NULL,
		PERIODO INT NOT NULL
);

CREATE TABLE DETALLE (
		NRO_ATOMICO INT PRIMARY KEY,
		URL NVARCHAR(60),
		DETALLE NVARCHAR(1000)
);

CREATE TABLE MENSAJES (
	ID_MENSAJE INT PRIMARY KEY IDENTITY(1,1),
	DE_USUARIO NVARCHAR(50) NOT NULL FOREIGN KEY REFERENCES	USUARIOS(MAIL),
	A_USUARIO NVARCHAR(50) NOT NULL FOREIGN KEY REFERENCES	USUARIOS(MAIL),
	PREGUNTA NVARCHAR(200) NOT NULL,
	RESPUESTA NVARCHAR(200) NOT NULL,
	ELEMENTO INT FOREIGN KEY REFERENCES ELEMENTO(NRO_ATOMICO),
	FECHA DATETIME
);

